### PR TITLE
Reminiaod dev

### PR DESCRIPTION
**Pull request by jpazzini**
- new JEC 23Sep2016V4
- included the modified VID modules in data and modified setup.sh accordingly
- included EGamma regression+smearer into Diboson; changed MET to 'slimmedMETsMuEGClean' for DATA
- included MuonTrackerSF
- Included NOW the VID files to Data (forgot in previous commit)

### CODE REVIEW

**Comment by jpazzini** [comment]
Still missing:
- merged Period12 + Period34 Muon trigger SF 
- Ele105 || Ele115 SF

**Comment by jpazzini** [comment]
Muon Trigger SF included with commit 1eb85a1

Still Missing:
- Ele105 || Ele115 SF

**Comment by jpazzini** [comment]
README updated

**Comment by MDallOsso** [comment]
Thanks Jacopo.
I would wait for Siew to submit his jobs (coming soon).
Then we can think about merging this PR if it is in-line with Lisa's work.

Martino

**Comment by jpazzini** [comment]
OK, please note however that so far we are commiting code into the REMINIAOD branch only, and not into the master.

I personally think however that the best idea could be first to check that everything is working as expected in REMINIAOD using the dedicated branch, and then move the "current version of the master" into a dedicated branch for RERECO, and then merge the REMINIAOD into the master (as the most up to date version of the code).

**Comment by MDallOsso** [comment]
okay. I thought it was for master.
I agree with you. we can merge and work on reminiaod branch.

**Comment by jpazzini** [comment]
Reverted back to V3 JEC and some cleanup in the code.
Still missing SingleEle triggers

**Pull request merged**
